server {
      listen 80;
      server_name ibmx.net www.ibmx.net;
      return 301 https://$host$request_uri;
  }

server {
      listen 443 ssl http2;
      server_name ibmx.net www.ibmx.net;

      ssl_certificate /etc/nginx/certs/origin.crt;
      ssl_certificate_key /etc/nginx/certs/origin.key;

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }
  }
